name: Deploy Breed Pred Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Environment
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST_NAME: ${{ secrets.SSH_USER }}
        USER_NAME: ${{ secrets.SSH_USER }}
      
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PUBLIC_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/ubuntu/Model"
        args: -r  # Recursively copy all files and directories

    - name: Run Gunicorn
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
        cd /home/ubuntu/Model && pip install -r requirements.txt && gunicorn -w 4 -b 0.0.0.0:8000 app:app"
        

