name: Deploy Application

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions runners support SCP, even for Windows deployments

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust requirements file name as needed

      - name: Deploy to Windows EC2
        uses: appleboy/win-scp-action@v1
        with:
          host: ${{ secrets.WINDOWS_HOST }}
          username: ${{ secrets.WINDOWS_USERNAME }}
          password: ${{ secrets.WINDOWS_PASSWORD }}  # Alternatively, use private key for authentication
          source: .  # Assuming your files are in the root directory of the repository
          target: "C:\\Users\\Administrator\\Desktop\\Model"  # Adjust target directory on the Windows EC2 instance
          args: -r  # Recursively copy all files and directories

      - name: Run app.py
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.WINDOWS_USERNAME }}@${{ secrets.WINDOWS_HOST }} "python C:\\Users\\Administrator\\Desktop\\Model\\app.py"
