name: Deploy Breed Pred Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==21.2.3
          pip install -r requirements.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy EC2
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.PUBLIC_IP }} "
        cd /SDGP-Model && 
        ls &&
        git pull &&
        /usr/bin/python3 -m pip install --upgrade pip==21.2.3 && 
        /usr/bin/python3 -m pip install -r requirements.txt && 
        gunicorn -w 4 -b 0.0.0.0:8000 app:app"


