name: Deploy Application

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions runners support SCP, even for Windows deployments

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust requirements file name as needed

      - name: Deploy to Windows EC2
        run: scp -o StrictHostKeyChecking=no -r . ${{ secrets.WINDOWS_USERNAME }}@${{ secrets.WINDOWS_HOST }}:"C:\\User\\Administrator\\Desktop\\Model"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run app.py
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.WINDOWS_USERNAME }}@${{ secrets.WINDOWS_HOST }} "python C:\\User\\Administrator\\Desktop\\Model\\app.py"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
