name: Deploy Breed Prediction Model 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Create docker image for the model
        run: docker build -t dilakshanchandrasena/petbay-model .
      - name: Push Model docker image to dockerhub
        run: docker push dilakshanchandrasena/petbay-model:latest


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Model image from docker hub
        run: docker pull dilakshanchandrasena/petbay-model:latest
      - name: Delete old container
        run: docker rm -f petbay-model-container
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name petbay-model-container dilakshanchandrasena/petbay-model
